### ISSUE TITLE
Error finding 'django.contrib.admin.apps.SimpleAdminConfig'

### ISSUE THREAD

**Issue by chrisdew** [jsocol/django-adminplus#40]
I've followed the first couple of instructions from the README, but get an error:
```
/usr/bin/python2.7 /home/chris/mrg/mrgdbui/manage.py runserver 8000
Traceback (most recent call last):
  File "/home/chris/mrg/mrgdbui/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 280, in execute
    translation.activate('en-us')
  File "/usr/lib/python2.7/dist-packages/django/utils/translation/__init__.py", line 130, in activate
    return _trans.activate(language)
  File "/usr/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 188, in activate
    _active.value = translation(language)
  File "/usr/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/usr/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
ImportError: No module named apps.SimpleAdminConfig

Process finished with exit code 1
```

I have installed django-adminplus with:
```
$ sudo pip install django-adminplus
Downloading/unpacking django-adminplus
  Downloading django_adminplus-0.5-py2.py3-none-any.whl
Installing collected packages: django-adminplus
Successfully installed django-adminplus
Cleaning up...
```

and added it to the INSTALLED_APPS:

# Application definition
```
INSTALLED_APPS = (
    'django.contrib.admin.apps.SimpleAdminConfig',
    #'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mrg',
    'adminplus',
)
```

What have I missed?

**Comment by jsocol** [comment]
Can you include versions for everything, especially Django and AdminPlus?

**Comment by chrisdew** [comment]
django-adminplus v0.5
django v1.6.1
ubuntu 14.04LTS

```
$ cat /usr/local/lib/python2.7/dist-packages/adminplus/__init__.py
"""
Django-AdminPlus module
"""

VERSION = (0, 5)
__version__ = '.'.join(map(str, VERSION))

$ cat /usr/lib/python2.7/dist-packages/django/__init__.py
VERSION = (1, 6, 1, 'final', 0)

def get_version(*args, **kwargs):
    # Don't litter django/__init__.py with all the get_version stuff.
    # Only import if it's actually called.
    from django.utils.version import get_version
    return get_version(*args, **kwargs)
```

**Comment by jsocol** [comment]
Django 1.6 isn't supported (by Django or by me) anymore. It may still work, but the Django app registry (`django.contrib.admin.apps.*` etc) was added in 1.7.

AdminPlus will probably still work with 1.6—just skip that step—but I'd really recommend moving to Django 1.8—or at the very, very least, getting to the latest 1.6. 1.6.1 is a very old, out-of-date version at this point.

**Comment by chrisdew** [comment]
Thanks, I'll try to work around it.  Django 1.6.1 is what comes with Ubuntu 12.04LTS.

**Comment by jsocol** [comment]
Django 1.6.1 came out over two years ago and the 1.6 branch has been officially unsupported since last April. It's really not a good idea to run it. I'd **strongly** recommend using [virtualenv](https://pypi.python.org/pypi/virtualenv) or another option to avoid using the OS package manager for Django. If the servers can't download directly from PyPI, there are other ways of moving the packages around, in particular Django ships wheels which should make it easier.
