### ISSUE TITLE
Django 2.1 support

### ISSUE THREAD

**Issue by stavlocker** [jsocol/django-adminplus#61]
Hi, I'd love to see django 2.1 get integrated. As far as I can tell there's a PR waiting from January 2018 https://github.com/jsocol/django-adminplus/pull/58 to support 1.10+ that just doesn't get merged. This package renders unusable for me unless something is done to support 2.1. I'm doing everything by the book and still getting the infamous `django.urls.exceptions.NoReverseMatch: Reverse for 'app_list' with keyword arguments '{'app_label': ''}' not found`.

**Comment by jsocol** [comment]
I've been digging into this and there's been a kind of surprising amount of movement in the admin config area of 2.0 and 2.1 and I'm not sure the best route forward here.

1. 2.0 changed a bunch of things around URL conf and how they get installed.
1. There are some details around installing `SimpleAdminConfig` vs `AdminConfig`
1. In 2.1, there's an option to create a [custom `AdminConfig`](https://docs.djangoproject.com/en/2.1/ref/contrib/admin/#overriding-the-default-admin-site) that can override the default admin site

**Comment by oliwarner** [comment]
Great point there @jsocol! I just wrote this little appconfig module for our purposes:

`admin.py`:
```
from django.contrib.admin.apps import AdminConfig
from django.contrib.auth.decorators import login_required

class AdminPlusConfig(AdminConfig):
    default_site = 'adminplus.sites.AdminSitePlus'

    def ready(self):
        super().ready()

        self.module.site.site_title = self.module.site.site_header = 'Our Magic Admin'
        self.module.site.login = login_required(self.module.site.login)
```

`settings.py`:
```
INSTALLED_APPS = [
    'admin.AdminPlusConfig',
]
```

`urls.py`:
```
from django.contrib import admin
urlpatterns = [
    path('admin/', include(admin.site.urls[:2], admin.site.urls[2])),
]
```

The site.urls is the only bit that's a bit funky now. If you could make that a Django 2-sensitive `@property`, that would really minimise the amount of hacking to get this in. Hell, you could even provide a little AppConfig, makes installation just two lines in `INSTALLED_APPS`.

**Comment by sivabudh** [comment]
I also have a problem about:

`django.template.exceptions.TemplateDoesNotExist: adminplus/index.html` 

when I try to access Django Admin by going visiting the `admin/` URL.

**Stack trace**
```
[08/Aug/2019 13:14:04] "GET /favicon.ico HTTP/1.1" 404 3012
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/Users/pac/.pyenv/versions/moen-37amem-django/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/pac/.pyenv/versions/moen-37amem-django/lib/python3.7/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/pac/.pyenv/versions/moen-37amem-django/lib/python3.7/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/Users/pac/.pyenv/versions/moen-37amem-django/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/pac/.pyenv/versions/moen-37amem-django/lib/python3.7/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/pac/.pyenv/versions/moen-37amem-django/lib/python3.7/site-packages/django/template/response.py", line 65, in resolve_template
    return get_template(template, using=self.using)
  File "/Users/pac/.pyenv/versions/moen-37amem-django/lib/python3.7/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: adminplus/index.html
```

**Comment by pkrefta** [comment]
Hi @jsocol - are there any plans to support Django 2.x ?

**Comment by jsocol** [comment]
I would love to get this updated. I imagine this situation described in [this comment](https://github.com/jsocol/django-adminplus/issues/61#issuecomment-468717203) has gotten better since we no longer have to worry about 2.0 and 2.1, only 2.2 and 3.0. I have not been working in Django day to day recently, though, so I'm not sure how easy it will be to support both 2.2 and 3.0.

I'm extremely open to patches that bring adminplus up to date with 2.2's— and hopefully 3.0's—admin module changes. I hope that the differences are smaller than existed between 2.{0,1,2}.
